# This is a basic workflow to help you get started with Actions

name: aws-cred

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write ## need by aws-actions/configure-aws-credentials
  contents: read
  issues: write  ## need by PR comment of terraform plan result
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # must have a name for status check
    name: aws-github-action

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: see pull_request_target
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo $EVENT_CONTEXT | jq .
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: ls root
        run: pwd && ls -l .
      
      - name: configure aws-cn credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::974398699107:role/github-action-role
          aws-region: us-west-2
      
      - name: who-am-i
        run: aws sts get-caller-identity     
